-- Phase 1: Foundation schema for real-time collaborative wedding planning.
-- Creates auth-linked profiles, wedding membership, per-section access grants,
-- and the generic change-log used for "last edited by" + version history/rollback
-- across every domain table added in later phases.

-- ============================================================================
-- Enums
-- ============================================================================

create type public.wedding_section as enum (
  'guests', 'vendors', 'budget', 'menu', 'checklist',
  'timeline', 'emergency_contacts', 'seating', 'mood_board',
  'custom_lists', 'wedding_info'
);

create type public.access_status as enum ('pending', 'approved', 'rejected', 'revoked');

-- ============================================================================
-- Core tables
-- ============================================================================

-- Extends Supabase's built-in auth.users; one row per authenticated person.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  email text not null,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.weddings (
  id uuid primary key default gen_random_uuid(),
  bride_name text not null default '',
  groom_name text not null default '',
  wedding_date date,
  currency_code text not null default 'INR',
  created_at timestamptz not null default now(),
  created_by uuid not null references public.profiles(id),
  last_edited_by uuid references public.profiles(id),
  last_edited_at timestamptz
);

-- Per-wedding membership. The creator becomes 'owner'; everyone else is 'member'.
-- Rows here are only ever created via the accept_wedding_invite RPC (see below),
-- never via direct client insert, so someone can't fabricate their own membership.
create table public.wedding_members (
  id uuid primary key default gen_random_uuid(),
  wedding_id uuid not null references public.weddings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('owner', 'member')),
  relationship text, -- free-text label e.g. 'Bride', 'Groom', 'Bride''s Mother' - display only, no access implication
  created_at timestamptz not null default now(),
  unique (wedding_id, user_id)
);

-- Shareable invite codes generated by the owner.
create table public.wedding_invites (
  id uuid primary key default gen_random_uuid(),
  wedding_id uuid not null references public.weddings(id) on delete cascade,
  invite_code text not null unique,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  max_uses int,
  use_count int not null default 0
);

-- The per-section grant table. One row per (wedding, user, section).
-- Standing access once approved -- no re-approval needed until revoked.
create table public.section_access (
  id uuid primary key default gen_random_uuid(),
  wedding_id uuid not null references public.weddings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  section public.wedding_section not null,
  status public.access_status not null default 'pending',
  can_write boolean not null default true,
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid references public.profiles(id),
  unique (wedding_id, user_id, section)
);

-- Generic audit/version-history log covering all domain tables (added in later phases).
create table public.change_log (
  id bigint generated always as identity primary key,
  wedding_id uuid not null references public.weddings(id) on delete cascade,
  table_name text not null,
  row_id uuid not null,
  operation text not null check (operation in ('insert', 'update', 'delete', 'rollback')),
  old_data jsonb,
  new_data jsonb,
  changed_by uuid references public.profiles(id),
  changed_at timestamptz not null default now()
);
create index change_log_row_idx on public.change_log (table_name, row_id, changed_at desc);
create index change_log_wedding_idx on public.change_log (wedding_id, changed_at desc);

-- ============================================================================
-- Helper functions (SECURITY DEFINER: only ever checks auth.uid(), never a
-- caller-supplied id, so it can't be used to check or leak other users' access)
-- ============================================================================

create or replace function public.is_wedding_member(p_wedding_id uuid)
returns boolean language sql stable security definer as $$
  select exists (
    select 1 from public.wedding_members
    where wedding_id = p_wedding_id and user_id = auth.uid()
  );
$$;

create or replace function public.is_wedding_owner(p_wedding_id uuid)
returns boolean language sql stable security definer as $$
  select exists (
    select 1 from public.wedding_members
    where wedding_id = p_wedding_id and user_id = auth.uid() and role = 'owner'
  );
$$;

create or replace function public.has_section_access(
  p_wedding_id uuid, p_section public.wedding_section, p_write boolean default false
)
returns boolean language sql stable security definer as $$
  select
    public.is_wedding_owner(p_wedding_id) -- owner always has full access, all sections
    or exists (
      select 1 from public.section_access
      where wedding_id = p_wedding_id
        and user_id = auth.uid()
        and section = p_section
        and status = 'approved'
        and (not p_write or can_write)
    );
$$;

-- ============================================================================
-- accept_wedding_invite RPC: the sole path to creating a non-owner membership row
-- ============================================================================

create or replace function public.accept_wedding_invite(p_invite_code text)
returns uuid language plpgsql security definer as $$
declare
  v_invite public.wedding_invites;
  v_member_id uuid;
begin
  select * into v_invite from public.wedding_invites where invite_code = p_invite_code for update;

  if v_invite is null then
    raise exception 'Invalid invite code';
  end if;
  if v_invite.expires_at is not null and v_invite.expires_at < now() then
    raise exception 'Invite code has expired';
  end if;
  if v_invite.max_uses is not null and v_invite.use_count >= v_invite.max_uses then
    raise exception 'Invite code has reached its usage limit';
  end if;

  insert into public.wedding_members (wedding_id, user_id, role)
  values (v_invite.wedding_id, auth.uid(), 'member')
  on conflict (wedding_id, user_id) do nothing
  returning id into v_member_id;

  update public.wedding_invites set use_count = use_count + 1 where id = v_invite.id;

  return v_invite.wedding_id;
end;
$$;

-- ============================================================================
-- Generic change-log trigger, attached per-domain-table starting in Phase 2
-- ============================================================================

create or replace function public.fn_log_change()
returns trigger language plpgsql security definer as $$
declare
  v_wedding_id uuid;
begin
  v_wedding_id := coalesce((to_jsonb(new)->>'wedding_id')::uuid, (to_jsonb(old)->>'wedding_id')::uuid);

  insert into public.change_log (wedding_id, table_name, row_id, operation, old_data, new_data, changed_by)
  values (
    v_wedding_id,
    TG_TABLE_NAME,
    coalesce((to_jsonb(new)->>'id')::uuid, (to_jsonb(old)->>'id')::uuid),
    lower(TG_OP),
    case when TG_OP in ('update', 'delete') then to_jsonb(old) else null end,
    case when TG_OP in ('insert', 'update') then to_jsonb(new) else null end,
    auth.uid()
  );

  if TG_OP = 'update' then
    new.last_edited_by := auth.uid();
    new.last_edited_at := now();
    return new;
  elsif TG_OP = 'delete' then
    return old;
  else
    return new;
  end if;
end;
$$;

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table public.profiles enable row level security;
create policy profiles_select on public.profiles for select using (true);
create policy profiles_update_self on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_insert_self on public.profiles for insert with check (id = auth.uid());

alter table public.weddings enable row level security;
create policy weddings_select on public.weddings
  for select using (public.is_wedding_member(id));
create policy weddings_insert on public.weddings
  for insert with check (created_by = auth.uid());
create policy weddings_update on public.weddings
  for update using (public.is_wedding_owner(id)) with check (public.is_wedding_owner(id));
-- wedding_info (bride/groom names, date, currency) is owner-only, always -- never delegable
-- via section_access, regardless of any 'wedding_info' section_access row that may exist.

alter table public.wedding_members enable row level security;
create policy wedding_members_select on public.wedding_members
  for select using (public.is_wedding_member(wedding_id));
-- No insert/update/delete policy for the authenticated role: membership rows are only
-- ever created by accept_wedding_invite() (owner's initial row is created by a trigger below).

alter table public.wedding_invites enable row level security;
create policy wedding_invites_select on public.wedding_invites
  for select using (public.is_wedding_owner(wedding_id));
create policy wedding_invites_insert on public.wedding_invites
  for insert with check (public.is_wedding_owner(wedding_id) and created_by = auth.uid());
create policy wedding_invites_delete on public.wedding_invites
  for delete using (public.is_wedding_owner(wedding_id));

alter table public.section_access enable row level security;
create policy section_access_select on public.section_access
  for select using (public.is_wedding_member(wedding_id));
create policy section_access_request on public.section_access
  for insert with check (
    user_id = auth.uid()
    and status = 'pending'
    and public.is_wedding_member(wedding_id)
  );
create policy section_access_owner_decide on public.section_access
  for update using (public.is_wedding_owner(wedding_id))
  with check (public.is_wedding_owner(wedding_id));

alter table public.change_log enable row level security;
create policy change_log_select on public.change_log
  for select using (
    public.has_section_access(wedding_id, (table_name::public.wedding_section))
  );
-- No insert/update/delete policy for authenticated role -> only fn_log_change()
-- (SECURITY DEFINER) can write. Prevents tampering with history from the client.

-- ============================================================================
-- Auto-create the owner's wedding_members row when a wedding is created
-- ============================================================================

create or replace function public.fn_wedding_created()
returns trigger language plpgsql security definer as $$
begin
  insert into public.wedding_members (wedding_id, user_id, role, relationship)
  values (new.id, new.created_by, 'owner', 'Owner');
  return new;
end;
$$;

create trigger trg_wedding_created
  after insert on public.weddings
  for each row execute function public.fn_wedding_created();

-- ============================================================================
-- Auto-create a profile row on first sign-in
-- ============================================================================

create or replace function public.fn_handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, display_name, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger trg_auth_user_created
  after insert on auth.users
  for each row execute function public.fn_handle_new_user();
